import type { Study, ResearchAssistant } from "./interfaces"

export const mockRAs: ResearchAssistant[] = [
  {
    id: '1',
    name: 'Sarah Chen',
    email: 'sarah.chen@university.edu',
    avatar: 'https://images.unsplash.com/photo-1494790108755-2616b9e0f97f?w=150&h=150&fit=crop&crop=face',
    totalHours: 45,
    pendingHours: 6.5,
    availability: ['Monday 9:00 AM - 12:00 PM', 'Wednesday 9:00 AM - 12:00 PM', 'Friday 9:00 AM - 11:00 AM']
  },
  {
    id: '2',
    name: 'Alex Kumar',
    email: 'alex.kumar@university.edu',
    avatar: 'https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?w=150&h=150&fit=crop&crop=face',
    totalHours: 32,
    pendingHours: 4,
    availability: ['Tuesday 10:00 AM - 1:00 PM', 'Thursday 10:00 AM - 2:00 PM']
  },
  {
    id: '3',
    name: 'Emma Wilson',
    email: 'emma.wilson@university.edu',
    avatar: 'https://images.unsplash.com/photo-1438761681033-6461ffad8d80?w=150&h=150&fit=crop&crop=face',
    totalHours: 28,
    pendingHours: 2.5,
    availability: ['Monday 2:00 PM - 5:00 PM', 'Wednesday 1:00 PM - 4:00 PM', 'Friday 9:00 AM - 11:00 AM']
  },
  {
    id: '4',
    name: 'Jason Lee',
    email: 'jason.lee@university.edu',
    avatar: 'https://images.unsplash.com/photo-1529626455594-4ff0802cfb7e?w=150&h=150&fit=crop&crop=face',
    totalHours: 20,
    pendingHours: 3,
    availability: ['Tuesday 8:00 AM - 10:00 AM', 'Thursday 1:00 PM - 4:00 PM']
  },
  {
    id: '5',
    name: 'Maria Gonzalez',
    email: 'maria.gonzalez@university.edu',
    avatar: 'https://images.unsplash.com/photo-1520813792240-56fc4a3765a7?w=150&h=150&fit=crop&crop=face',
    totalHours: 38,
    pendingHours: 5,
    availability: ['Wednesday 10:00 AM - 2:00 PM', 'Friday 1:00 PM - 4:00 PM']
  },
  {
    id: '6',
    name: 'Daniel Park',
    email: 'daniel.park@university.edu',
    avatar: 'https://images.unsplash.com/photo-1500648767791-00dcc994a43e?w=150&h=150&fit=crop&crop=face',
    totalHours: 17,
    pendingHours: 2,
    availability: ['Monday 8:00 AM - 11:00 AM']
  },
  {
    id: '7',
    name: 'Luna Patel',
    email: 'luna.patel@university.edu',
    avatar: 'https://images.unsplash.com/photo-1552058544-f2b08422138a?w=150&h=150&fit=crop&crop=face',
    totalHours: 25,
    pendingHours: 1,
    availability: ['Tuesday 2:00 PM - 5:00 PM', 'Thursday 9:00 AM - 12:00 PM']
  },
  {
    id: '8',
    name: 'Noah Johnson',
    email: 'noah.johnson@university.edu',
    avatar: 'https://images.unsplash.com/photo-1544725176-7c40e5a2c9f9?w=150&h=150&fit=crop&crop=face',
    totalHours: 29,
    pendingHours: 3,
    availability: ['Wednesday 3:00 PM - 6:00 PM']
  },
  {
    id: '9',
    name: 'Olivia Martinez',
    email: 'olivia.martinez@university.edu',
    avatar: 'https://images.unsplash.com/photo-1524504388940-b1c1722653e1?w=150&h=150&fit=crop&crop=face',
    totalHours: 22,
    pendingHours: 3.5,
    availability: ['Thursday 11:00 AM - 3:00 PM']
  },
  {
    id: '10',
    name: 'Ethan Wright',
    email: 'ethan.wright@university.edu',
    avatar: 'https://images.unsplash.com/photo-1527980965255-d3b416303d12?w=150&h=150&fit=crop&crop=face',
    totalHours: 19,
    pendingHours: 1.5,
    availability: ['Monday 1:00 PM - 4:00 PM', 'Friday 9:00 AM - 12:00 PM']
  }
];


export const mockStudies: Study[] = [
  {
    id: '1',
    title: 'Cognitive Behavior Study',
    description: 'Observational study on decision-making patterns in college students',
    date: '2025-11-20',
    startTime: '10:00 AM',
    endTime: '12:00 PM',
    location: 'Psychology Lab A',
    assignedRA: 'Sarah Chen',
    status: 'completed',
  },
  {
    id: '2',
    title: 'Social Media Impact Research',
    description: 'Long-term study on social media usage and academic performance',
    date: '2025-11-18',
    startTime: '2:00 PM',
    endTime: '4:00 PM',
    location: 'Research Center B',
    assignedRA: 'Sarah Chen',
    status: 'assigned',
  },
  {
    id: '3',
    title: 'Memory Formation Study',
    description: 'EEG study examining memory consolidation during sleep',
    date: '2025-11-15',
    startTime: '9:00 AM',
    endTime: '12:00 PM',
    location: 'Neuroscience Lab',
    assignedRA: '',
    status: 'open',
  },
  {
    id: '4',
    title: 'Attention Span Measurement',
    description: 'Study on sustained attention across digital tasks',
    date: '2025-11-22',
    startTime: '1:00 PM',
    endTime: '3:00 PM',
    location: 'Cognitive Science Lab',
    assignedRA: 'Emma Wilson',
    status: 'assigned',
  },
  {
    id: '5',
    title: 'Sleep Cycle Movement Study',
    description: 'Wearable-based measurement of REM/NREM transitions',
    date: '2025-11-25',
    startTime: '8:00 AM',
    endTime: '10:00 AM',
    location: 'Sleep Center',
    assignedRA: '',
    status: 'open',
  },
  {
    id: '6',
    title: 'Stress Response Assessment',
    description: 'Study using cortisol tracking during exams',
    date: '2025-11-28',
    startTime: '3:00 PM',
    endTime: '5:00 PM',
    location: 'Biology Lab 3',
    assignedRA: 'Jason Lee',
    status: 'assigned',
  },
  {
    id: '7',
    title: 'Short Term Memory Test',
    description: 'Study on auditory vs visual recall',
    date: '2025-11-29',
    startTime: '11:00 AM',
    endTime: '1:00 PM',
    location: 'Psychology Building 2C',
    assignedRA: 'Olivia Martinez',
    status: 'completed',
  },
  {
    id: '8',
    title: 'VR Immersion Impact Study',
    description: 'Testing cognitive fatigue in extended VR environments',
    date: '2025-12-01',
    startTime: '4:00 PM',
    endTime: '7:00 PM',
    location: 'Tech Innovation Lab',
    assignedRA: '',
    status: 'open',
  },
  {
    id: '9',
    title: 'Nutritional Habits and Focus',
    description: 'Tracking focus quality after different meal types',
    date: '2025-12-03',
    startTime: '9:00 AM',
    endTime: '11:00 AM',
    location: 'Nutrition Wing A',
    assignedRA: 'Maria Gonzalez',
    status: 'assigned',
  },
  {
    id: '10',
    title: 'Pain Tolerance Study',
    description: 'Testing pain thresholds under cold pressure',
    date: '2025-12-04',
    startTime: '12:00 PM',
    endTime: '2:00 PM',
    location: 'Medical Research Center',
    assignedRA: '',
    status: 'open',
  },
  {
    id: '11',
    title: 'Caffeine Sensitivity Test',
    description: 'Measuring reaction time after caffeine intake',
    date: '2025-12-06',
    startTime: '10:00 AM',
    endTime: '1:00 PM',
    location: 'Lab C14',
    assignedRA: 'Ethan Wright',
    status: 'assigned',
  },
  {
    id: '12',
    title: 'Group Problem Solving Study',
    description: 'Observing teamwork strategies under pressure',
    date: '2025-12-07',
    startTime: '3:00 PM',
    endTime: '6:00 PM',
    location: 'Collaboration Center Room 5',
    assignedRA: 'Luna Patel',
    status: 'assigned',
  },
  {
    id: '13',
    title: 'Music and Mood Research',
    description: 'Testing emotional response to different music genres',
    date: '2025-12-10',
    startTime: '11:00 AM',
    endTime: '2:00 PM',
    location: 'Sound Lab',
    assignedRA: '',
    status: 'open',
  },
  {
    id: '14',
    title: 'Reaction Time Comparison Study',
    description: 'Comparing keyboard vs touch reaction times',
    date: '2025-12-11',
    startTime: '1:00 PM',
    endTime: '3:00 PM',
    location: 'Tech Center A',
    assignedRA: 'Daniel Park',
    status: 'assigned',
  },
  {
    id: '15',
    title: 'Color Perception Study',
    description: 'Testing perception differences under varied lighting',
    date: '2025-12-12',
    startTime: '9:00 AM',
    endTime: '12:00 PM',
    location: 'Optics Lab',
    assignedRA: '',
    status: 'open',
  },
  {
    id: '16',
    title: 'Student Productivity Monitoring',
    description: 'Tracking productivity tools used during studying',
    date: '2025-12-13',
    startTime: '2:00 PM',
    endTime: '5:00 PM',
    location: 'Research Center C',
    assignedRA: 'Noah Johnson',
    status: 'assigned',
  },
  {
    id: '17',
    title: 'Emotional Recognition Test',
    description: 'Facial expression recognition accuracy test',
    date: '2025-12-14',
    startTime: '10:00 AM',
    endTime: '12:00 PM',
    location: 'Behavioral Lab 2',
    assignedRA: '',
    status: 'open',
  },
  {
    id: '18',
    title: 'Learning Strategy Study',
    description: 'Evaluating study methods on long-term retention',
    date: '2025-12-15',
    startTime: '1:00 PM',
    endTime: '4:00 PM',
    location: 'Education Lab',
    assignedRA: 'Sarah Chen',
    status: 'assigned',
  },
  {
    id: '19',
    title: 'Decision-Making Under Stress',
    description: 'Tracking choices under time pressure',
    date: '2025-12-16',
    startTime: '8:00 AM',
    endTime: '10:00 AM',
    location: 'Psych Lab D',
    assignedRA: '',
    status: 'open',
  },
  {
    id: '20',
    title: 'Digital Learning Tools Impact',
    description: 'Comparing digital vs physical learning tools',
    date: '2025-12-18',
    startTime: '2:00 PM',
    endTime: '5:00 PM',
    location: 'Innovation Center Room 9',
    assignedRA: 'Emma Wilson',
    status: 'completed',
  }
];
